[tool.black]
line-length = 100
target-version = [
    'py39',
]
include = 'connectome_manipulator\/.*\.py$|tests\/.*\.py$|doc\/source\/conf\.py$|setup\.py$'

[tool.pytest.ini_options]
pythonpath = [
  "."
]

