name: Run tox

on:
    pull_request:
    push:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:

    - uses: actions/checkout@v4
      with:
        repository: BlueBrain/parquet-converters
        path: parquet-converters
        submodules: true

    - name: Set up Apache Arrow repositories
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates lsb-release wget
        wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
        sudo apt-get install -y ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
        sudo apt-get update

    - name: Install build dependencies
      run: |
        sudo apt-get install -y cmake g++ libhdf5-openmpi-dev librange-v3-dev ninja-build nlohmann-json3-dev
        sudo apt-get install -y libarrow-dev libparquet-dev

    - name: Configure and build
      run: |
        cd parquet-converters
        cmake -B build -S . -GNinja \
          -DCMAKE_INSTALL_PREFIX=$PWD/install \
          -DCMAKE_CXX_COMPILER=$(which mpicxx)
        cmake --build build
        ctest --test-dir build --output-on-failure
        cmake --install build
        echo "$PWD/install/bin" >> $GITHUB_PATH
        echo $GITHUB_PATH

    - name: Check dependencies
      run: |
        echo $GITHUB_PATH
        echo $PATH
        echo "parquet2hdf5 --version"
        parquet2hdf5 --version

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install tox-gh-actions

    - name: Run tox
      run: |
        tox -e lint
        tox -e coverage
        tox -e py
        tox -e functional

    - name: Upload to codecov
      if: ${{matrix.python-version == '3.10'}}
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: false
        files: ./coverage.xml
        flags: pytest
        name: "connectome-manipulator-py310"
